### ISSUE TITLE
Dropped connection during create()

### ISSUE THREAD

**Issue by gothub** [DataONEorg/rdataone#131]
@amoeba and @couture322 have both reported that they have experienced dropped connections
while attempting to upload many and sometimes large files to DataONE using create() (now createObject()). This problem has been frequently seen while uploading a series of relatively
small files, then uploading a file between 200-500MB. This happens with the upload occuring
from aurora.nceas to dev.nceas, which is a 1Gbit connection. The error printed is:
```
Error in .local(mnode, pid, ...) : 
  Error creating urn:uuid:3af3c699-5160-4c73-88fa-a2ea297628e1: Could not resolve multipart files: Processing of multipart/form-data request failed. Stream ended unexpectedly
```

**Comment by sbpcs59** [comment]
After much testing I have not been able to reliably recreate this problem, even with 4GB files
over a wireless connection (100Mbit connection). The problem might only occur for other users
when the servers are busy. In the case of uploading from aurora.nceas to dev.nceas, it isn't
clear that network congestion is an issue.

In an effort to rule out at least one possible problem, I've turned on TCP keepalive by adding
a keep-alive header for dataone R client POST requests. This has been implemented in
commit b847fc7a29f26caeb386925abef3465183d3c1ae

**Comment by couture322** [comment]
Thanks for looking into this @sbpcs59. I have been trying to find patterns but nothing has stuck out for me. Sometimes the same script on the same files works then right after it doesn't. One thing to note is that it might not actually be the traffic since I was unsuccessful at all last weekend after various tries. Unless there was also a lot of traffic on Saturday (2/27/16) as well.  

Otherwise it had failed on different files, after a different number of uploads, different sizes, etc. I'll keep an eye out for any consistencies.

**Comment by sbpcs59** [comment]
Setting the HTTP header "Connection: keep-alive" was not turning on TCP keepalive probe packets.
This unfortunately named HTTP header does not affect the TCP keepalive setting, but instead 
causes the connection to not be closed, or *persisted* after the server has responded to the request
(should have called it "Connection: persist"). I've updated the POST mechanism in dataone to 
now set TCP keepalive packets using `httr::config(tcp_keepalive = as.integer(1))` which uses the
default tcp_keepidle and tcp_keepintvl set by httr. This has been updated in commit b8c0c2fa6a5c63440460bf3c7ba9e85ae543ae76

So, I'm at a loss to explain why we haven't seen "stream ended", connection closed problems recently.

httr tcp_keepalive corresponds to curl tcp_keepalive, see https://curl.haxx.se/libcurl/c/CURLOPT_TCP_KEEPALIVE.html

**Comment by amoeba** [comment]
Good sleuthing, @sbpcs59.

I was only ever able to reliably generated the errors if I conditioned my network link severely. Otherwise it was rare. Considering that, and given that I'm doing inserts from VM to VM, not seeing these errors during my thousands of inserts is not surprising. I bet the link isn't without data for even a millisecond.

**Comment by gothub** [comment]
Haven't seen this problem since commit b8c0c2fa6a5c63440460bf3c7ba9e85ae543ae76 in the first
week of March, so I'm calling this resolved.
