### ISSUE TITLE
Evaluate namespacing authentication tokens

### ISSUE THREAD

**Issue by sbpcs59** [DataONEorg/rdataone#139]
Authentication tokens created in a development environment (e.g. generated from search-stage.test.dataone.or) cannot be used for authentication in the production environment, and
visa-versa. Switching between tokens generated for production and testing can be
confusing and error-prone. The namespacing would be applied to the R options, for example,

```
options(authentication_token=c("prod:<token_value>", "dev:<token_value")
```

The default, without namespace would continue to be used, but might be sent to the
wrong environment, i.e. minted in dev, sent to prod:

```
options(authentication_token="<token_value>")
```

**Comment by amoeba** [comment]
I'm pretty new to this package's development but I wonder if this is a good time to ask: Have approaches for providing the user's D1 token to the package other than `options()` been considered? When I saw this package's use of `options()` to set the token for the first it was the first time I've seen an R package use `options()` in this way. Is there a history to this choice?

In my experience, access tokens like the D1 tokens (PAT, oauth secrets, etc) are set using environmental variables rather than `options()` and packages make use of the value of the env var to establish the presence and value of the token(s). An example of two high-visibility R packages using env vars to store tokens would be https://github.com/gaborcsardi/gh or https://github.com/sckott/analogsea but there are many more.

Using environment variables in this way aligns to the recommendations provided by http://12factor.net/config which I see endorsed often. 

Thoughts?

**Comment by cboettig** [comment]
I agree that env vars (.Renviron) are more natural to me as well, but
options() is not uncommon here, and may be more user friendly.

I think the authentication method should select the correct token (staging,
prod) based on the env specified in the function.  No need to have the user
make sure they give the right token for the right env.

I would use underscores, not colons, to namespace the token, just like you
see in, say, how dplyr sets options.  R plays badly with variable names in
options with colons because they must always be quoted, while it is typical
to omit the quotes (like you do in your copy/paste code from dataone web
interface for saving options)

On Thu, Mar 17, 2016, 3:50 PM Bryce Mecum <notifications@github.com> wrote:

> I'm pretty new to this package's development but I wonder if this is a
> good time to ask: Have approaches for providing the user's D1 token to the
> package other than options() been considered? When I saw this package's
> use of options() to set the token for the first it was the first time
> I've seen an R package use options() in this way. Is there a history to
> this choice?
>
> In my experience, access tokens like the D1 tokens (PAT, oauth secrets,
> etc) are set using environmental variables rather than options() and
> packages make use of the value of the env var to establish the presence and
> value of the token(s). An example of two high-visibility R packages using
> env vars to store tokens would be https://github.com/gaborcsardi/gh or
> https://github.com/sckott/analogsea but there are many more.
>
> Using environment variables in this way aligns to the recommendations
> provided by http://12factor.net/config which I see endorsed often.
>
> Thoughts?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/DataONEorg/rdataone/issues/139#issuecomment-198114231>
>
-- 

http://carlboettiger.info

**Comment by cboettig** [comment]
Just to clarify (now that I'm at a computer instead of a cell phone): I would suggest something like this:

```
options(dataone_prod_token = "XXX")
options(dataone_staging_token = "YYY")
```

I don't think it's ideal to just call the option (or environmental variable) `authentication_token`, the usual practice seems to be to include the service or package name in the token variable name.  

Likewise since staging and production are essentially different api endpoints with different tokens, I think it is cleanest just to make this explicit in the token name, like above, and have the function choose the right option (or env var) for the whichever endpoint it is trying to hit.   Sound good? (sorry if that didn't need more clarifying)

**Comment by sbpcs59** [comment]
@cboettig I'll have to check this with the DataONE engineers, but I'm fairly certain that tokens can
be either production or development, i.e. a token generated in any development env can work in any development env, so I would suggest:

```
options(dataone_prod_token = "xxx")
options(dataone_dev_token="yyy")
````

**Comment by cboettig** [comment]
:+1:  Looks good to me

**Comment by mbjones** [comment]
I proposed using options because 1) I liked how FigShare did the same thing, and 2) changing environment variables is unfamiliar to many users (esp on Windows), whereas options() is just another R command.  

I like the use of two different names for the options for the prod and dev environments.  Its really production environment versus the test environments, so maybe these should be named:

```
options(dataone_prod_token = "xxx")
options(dataone_test_token="yyy")
```
or maybe:
```
options(dataone_token = "xxx")
options(dataone_test_token="yyy")
```

**Comment by cboettig** [comment]
Note that you can get and set environmental variables from R if you want using `Sys.getenv()` and `Sys.setenv()`, so no need for a windows user to mess with `.Renviron`, or worse, shell environment variables.  Of course those are available too via `Sys.getenv()`.

That said, I'm fine with `options()`, I think it's pretty common (and more familiar to more R users).

**Comment by sbpcs59** [comment]
Separate tokens for production and test environments have been implemented using the
R options:

```
options(dataone_token = "<production environment token value>")
options(dataone_test_token = "<test environment token value>")
```
These changes were made in commit 68948e78229aa577235fad609b2e88bc72dfcb00

The old option value "authentication_token" is no longer checked.

A ticket has been logged for metacatui to update the authentication option that is generated
from the user's profile page, described here: https://projects.ecoinformatics.org/ecoinfo/issues/6992
