### ISSUE TITLE
parameter issue with d1Client

### ISSUE THREAD

**Issue by jeanetteclark** [DataONEorg/rdataone#166]
I came upon a bug using d1Client. The code:

cn <- CNode('STAGING2')
mn <- getMNode(cn,'urn:node:mnTestKNB')
d1c <- D1Client(cn,mn)

returns an empty d1c@mn

this:
d1c <- D1Client('STAGING2', 'urn:node:mnTestKNB')

returns d1c as expected. According to the help page both ways of running the function should work

**Comment by gothub** [comment]
@jeanetteclark I think the issue here is that rdataone needs a new constructor that accepts (CNode, MNode) arguments and creates the D1Node object accordingly. The constructors are convenience 
methods that call the `initialize()` function, so until the new constructor is available, it's perfectly
legal to use this:

```
cn <- CNode('STAGING2')
mn <- getMNode(cn,'urn:node:mnTestKNB')
d1c <- new("D1Client", cn,mn)
str(d1c@mn@identifier)
```

You can view the documentation for this with `?"D1Client-initialize"`.

It also looks like `D1Client-initialize` isn't properly linked into the rdataone documentation, so I'll 
fix that too. The `initialize()` documentation should be linked to 'See Also' from `?D1Client`.

**Comment by gothub** [comment]
Added constructor `D1Client("CNode", "MNode")` in commit 954c13ceaf83d7a0635a50ad04c2ef061e9bf10c
