### ISSUE TITLE
'' Error calling getPackage: ''

### ISSUE THREAD

**Issue by GloryPassarello** [DataONEorg/rdataone#177]
I am running this code for download a package just following instructions reported on `vignette("download-data")`

`library(dataone)
cn <- CNode("PROD")`

`queryParamList <- list(q="id:doi*", 
                       rows="15", 
                       fq="title: Cumulative human impacts", 
                       fl="id,title,dateUploaded,abstract,datasource,size,entityName,entityType")`

`result <- query(cn, queryParamList, as="data.frame", parse=FALSE)`

#taking package id
`id_package <- result[2, 'id']`

#get member id
`locations <- resolve(cn, id_package)`
`mnId <- locations$data[1, "nodeIdentifier"]`
`mn_example <- getMNode(cn, mnId)`

#download
`bagitFileName <- getPackage(mn_example, identifier =id_package)`

And I got that error:

`Your login certificate is missing or unreadable. You must login again via CILogon using 'dataone::downloadCert(CertificateManager())'
Attempting to call as public user without being authenticated.`
`Warning message:`
`In .local(x, ...) :`
`  Error calling getPackage: The given pid doi:10.5063/F1DR2SDD is not a package id (resource map id). Please use a package id instead.`

What is it going on wrong?

**Comment by gothub** [comment]
@GloryPassarello The `getPackage` method is a bit strict regarding the identifier that it
needs, which is the "package" identifier. In this case the id that I think you want is "urn:uuid:9605bb3e-a173-42d6-a056-8c47ba8aa540", which you can see in the blue title bar in the package member table at https://knb.ecoinformatics.org/#view/doi:10.5063/F1DR2SDD

However, when I specify the id that 'getPackage()' can use, I get the error:

```
 Error calling getPackage: READ not allowed on rescaled_2008_one_population_mol_20150713212253
```

And the download stops.

This indicates that one of the package members isn't readable to the public. I will contact the
package author to correct this problem.

Because this package is large, the 'Download All' button for it is greyed out, so I believe that 
your best option at this point is to click each of the download buttons for each package
member.

I'll also enter a github issue to look into making the `getPackage()` call easier to use, so that
you can either specify the package id or the metadata it (as you had done).

Let me know if you have any additional questions about getting the data you need.

**Comment by GloryPassarello** [comment]
@gothub Many thanks for your fast response and for your time. 
So is the error you got not related with `Your login certificate is missing or unreadable `?
I've seen that I can find the Id you gave me "urn:uuid:9605bb3e-a173-42d6-a056-8c47ba8aa540" with the name of `resourceMap` and with that id  download works also for other packages.

I fear that the vignette for downloading data is not 100% clear...

**Comment by gothub** [comment]
@GloryPassarello The `READ not allowed` error indicates that I don't have permission to
read the data with the identifier `rescaled_2008_one_population_mol_20150713212253`, and
so my user identity doesn't grant me access, even though I do have a current DataONE
authentication token. Other data in this package are set to be public readable, and so should the
above mentioned data, so once the investigator owning this package changes permission to 'public' read, anyone will be able to access it. I talked with the package owner yesterday and they should be able to change access in a day or two.

Are you able to download this package, either via the R client or via the link mentioned above
with the 'Download' link for each data file?

Yes, the documentation certainly could use improvements, thanks for the feedback.

**Comment by GloryPassarello** [comment]
@gothub Yes, Now the download for the package "`urn:uuid:9605bb3e-a173-42d6-a056-8c47ba8aa540`" starts with `getPackage()` but I cannot finish it:I mean it takes forever. 
Maybe the package is too much big!
Thank you very much to help me on this and to fix `READ not allowed` issue !!

**Comment by gothub** [comment]
I believe that this issue has been resolved.
