### ISSUE TITLE
Feedback on documentation of 'package update' functionality

### ISSUE THREAD

**Issue by gothub** [DataONEorg/rdataone#193]
@amoeba had the following comments regarding the `update-package` vignette:

...looks good. it seems like you can do a lot and that the added functionality would be useful
I had some general comments,

1. High-level, I felt a bit overwhelmed by the length of the document
2. I was surprised when the first part of the 'Updating a package' involved 'Uploading a package'. Is that latter topic covered elsewhere and could it be linked?
3. I felt confused about what the `filename` and `suggestedFilename` args were.
4. I got confused about how much of the document was about authoring EML and had nothing to do with the main task.

**Comment by gothub** [comment]
I'll address each point separately:

1. Yeah, most of the first section 'Create a Package and Upload to DataONE' could be removed. I wanted the user to be really familiar with the data package so that they could see clearly what needed to be updated, but maybe this was overkill.

2. Yep, good point. As stated in reply to 1., I'll remove section 1 and incorporate any salvageable bits into 'upload-data' vignette, so the the update and update use the same package.

3. I'll add an explanation to the docs, but `filename` is the DataObject slot thayt holds the data file associated with the DataObject, and `suggestedFilename` is the SystemMetadata slot that contains the filename that DataONE will use to name the file on download.

4. Yep, this is a tough one. There is a certain amount of EML manipulation that has to happen before upload to allow MetacatUI to fully display the data. In particular, the EML `//physical/distribution/online/url` xpath has to contain the current pid resolvable url so that MetacatUI can link the metadata index and detail views. Also, with out this link, no provenance can be displayed in the detail views. WIthout that pid, metacatui has no way to connect the detail info for package members and the pid that it describes.

All the EML in the examples is to establish this link between the pid and detail info. I'm not sure how else this can be done programatically, unless the user knows all the pids for each member of a package ahead of time and has already edited their EML.

So ideas on how to improve this, or alternative approaches would be greatly welcomed.

**Comment by amoeba** [comment]
3. By

> filename is the DataObject slot thayt holds the data file associated 

do you mean the path to the file on disk? What if that argument was renamed to `file` or `path` and the argument for setting the `SystemMetadata` `filename` slot could be `filename`. I suggest `path` (though `file` is the R convention) to avoid the name overlap which would cause numerous problems (R and human).  

I think the 'suggested' part is confusing. At first I thought it meant something like "try to use this as a filename but if it contains characters that some file system(s) can't handle, try for something close".

4. I would remove everything about EML and replace it with a short note like "Your metadata may need updating if it describes any of the Data Objects we just removed". I think this would streamline the task for users who don't have any EML Entities in their EML in the first place (common) and tidy things up. Also, since DataONE supports standards other than EML, any EML-specific stuff could be thought of as a specialization and could be documented elsewhere.

What do you think?

**Comment by gothub** [comment]
@amoeba 

Regarding item 3.:
- The DataObject slot named `filename` specifies the file path that contains the 
data that the DataObject object wraps. I don't think this should change, as the slot names are part of the public API, and this has been published in CRAN releases.
- The DataObject init param named `filename` matches the corresponding slot named `filename`
- The SystemMetadata slot named `fileName` specifies the suggested filename for DataONE to use when it is downloading a file. The mixed case name is the same as the serialized v2 sysmeta XML element name, and is consistent with all other SystemMetadata.R slot names that are mixed case.
- The DataObject init param named `suggestedFilename` corresponds to the SystemMetadata `fileName` slot. I thought that this parameter should be sufficiently different than `filename`, so calling it `fileName` or `file` or similiar might be more confusing.

I hope that additional explanation and additional examples in the docs can make this clearer.

Regarding item 4.
Yep, agreed - including the EML updating/editing with the package update workflow is too much
info, so I'll remove it and include a separate section that details how to update EML.

**Comment by amoeba** [comment]
> The DataObject slot named filename specifies the file path that contains the
data that the DataObject object wraps.

Ah, okay. Maybe part of the confusion for me was because I've never actually used the `DataObject` class and because of the similarity between `SystemMetadata`'s `fileName` and `DataObject`'s `filename` slot which are related but distinct. I really think `suggestedFilename` is confusing for semantic reasons.

>  I don't think this should change, as the slot names are part of the public API, and this has been published in CRAN releases.

Fair enough. This is probably more important than point.

Thanks for the detailed responses. Let me know if you want me to take a look at the next draft.

**Comment by gothub** [comment]
The 'upload-data' and 'update-package' vignettes have been re-written based on feedback from
@amoeba - the steps to update a package have been greatly simplified and (hopefully) clarified,
and the details of updating metadata have been moved to a new section. The same sample package
is used in both `upload-data` and `update-package`, so that a new package doesn't need to be introduced in `update-package`. 

In addition, the R help documentation for `DataObject` has been improved to better explain the
`filename` and `suggestedFilename` arguments. The latter name isn't great, but it does match the
DataONE documentation and is fully explained in the R help.

**Comment by gothub** [comment]
@amoeba Regarding the `suggestedFilename` parameter, see @mbjones solution
[here](https://github.com/ropensci/datapack/issues/86)

**Comment by amoeba** [comment]
LGTM. Thanks @gothub
