### ISSUE TITLE
Using the query function to search DataOne by doi

### ISSUE THREAD

**Issue by LiamBurke24** [DataONEorg/rdataone#194]
Hi all, quick thanks to @gothub & @amoeba, for all their help last week! 

I have been working on a script to query DataOne by doi via your package. Unfortunately, I am having a difficult time co-opting the query function to make this work with the vague documentation on the arguments of the query function. 

For example, 
```
library(dataone)
doi <- "doi:10.6073/pasta/6b03a068eb72af9b2ba14d633c9cb60c"
cn <- CNode("PROD") 
result <- query(cn, solrQuery = doi, encode = FALSE, as = "data.frame", parse = FALSE)
```
successfully returns a data.frame of results, but is limited to 10 entries. Also, these entries change every time the query is performed leading me to believe that there are more than 10 relevant results. 

I attempted to modify the code to return more results in the following way: 
```
cn <- CNode("PROD") 
queryParams <- list(q = "id:doi:10.6073/pasta/6b03a068eb72af9b2ba14d633c9cb60c", rows = 15)
result <- query(cn, searchTerms = queryParams, 
                encode = FALSE, as = "data.frame", parse = FALSE)
```
Unfortunately, this did not fill the data.frame. 

Any suggestions would be helpful, but specifically, which argument can take a doi input? 

Many thanks in advance for your help!

**Comment by amoeba** [comment]
Hey @LiamBurke24, the `query` function in the `dataone` package executes a Solr query so the details of creating a valid Solr query are crucial. In this case, because the identifier "doi:10.6073/pasta/6b03a068eb72af9b2ba14d633c9cb60c" contains one of the reserved characters (":"), it the query needs to be modified a bit:

```r
query(cn, 'q=id:"doi:10.6073/pasta/6b03a068eb72af9b2ba14d633c9cb60c"')
```

The above is one way to do it (note the mixed use of ' and "), but there are a few more ways (See the Solr docs).

**Comment by LiamBurke24** [comment]
@amoeba Thanks so much. I'm glad there was a simple fix!
