### ISSUE TITLE
Confusing error message on incorrect D1Client call

### ISSUE THREAD

**Issue by amoeba** [DataONEorg/rdataone#203]
I was trying to set up a D1Client to submit to a test MN and got an error message I think could be greatly improved:

```
> D1Client("STAGING", "urn:node:testARCTIC")
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “NULL” is not valid for @‘mn’ in an object of class “D1Client”; is(value, "MNode") is not TRUE
In addition: Warning message:
In .local(x, ...) : Member node urn:node:testARCTIC not found.
```

The first error implies the code could be made a bit more defense so as to avoid trying to assign NULL to the `mn` slot on the client instance.
The second error might instead say something like:

> The supplied member node identifier of 'urn:node:testARCTIC' was not found in the 'STAGING' environment. Please check that you've entered the member node identifier correctly and that the member node is in the STAGING environment.

**Comment by mbjones** [comment]
Agreed.  Thanks for the report.

The error message might also point out that the listNodes() function can be used to get a list of node identifiers in a given environment.

**Comment by gothub** [comment]
Fixed in commit 81bfe66c3f829ee0a64b1d98a418506707c00829

**Comment by earnaud** [comment]
Hi !
I got an error similar to the one in this issue (and therefore do not want to open a new one). 
I tried to download a DP with:
```
d1c <- D1Client("STAGING", "urn:node:mnTestARCTIC")
dp <- getDataPackage(d1c, "urn:uuid:5374d070-e834-4690-987f-d0d0789360b5")
```
which shall target [this data package](https://test.arcticdata.io/view/urn%3Auuid%3A5374d070-e834-4690-987f-d0d0789360b5).
Since I do not any other identifier for the pacakge, I used the uuid, although the example for `getDataPackage()` uses a pid.
I get the following error message:
`Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “NULL” is not valid for @‘resmapId’ in an object of class “DataPackage”; is(value, "character") is not TRUE`
which can be similar to many issues on other R repos. (see [this google search](https://www.google.com/search?q=+assignment+of+an+object+of+class+%E2%80%9CNULL%E2%80%9D+is+not+valid+for&client=ubuntu&channel=fs&biw=1848&bih=968&sxsrf=ALeKk02X41eZNGjZ05L6k1A2W5k3gnYKQg%3A1629102084324&ei=BCAaYZmJE6idlwSPxYmQDA&oq=+assignment+of+an+object+of+class+%E2%80%9CNULL%E2%80%9D+is+not+valid+for&gs_lcp=Cgdnd3Mtd2l6EAMyBQgAEMsBMgQIABAeOgcIABBHELADSgUIOhIBMkoECEEYAFCMJViMJWCBJmgCcAJ4AIABVogBpAGSAQEymAEAoAEByAEIwAEB&sclient=gws-wiz&ved=0ahUKEwiZm6eYjrXyAhWozoUKHY9iAsIQ4dUDCA0&uact=5)).

Thanks for any help you will be able to provide !

**Comment by amoeba** [comment]
Hi @earnaud, thanks for the report. 

I think we could improve the error handling here. It looks like what's going on is that `urn:uuid:5374d070-e834-4690-987f-d0d0789360b5` is not in a Data Package (it's just a standalone science metadata object) and `getDataPackage` isn't checking for this. According to the help file on the method, it should be returning `NULL`.

The error is similar to the original error but the cause is different so I'm going to open a new issue.

How was `urn:uuid:5374d070-e834-4690-987f-d0d0789360b5` created? Were you using our metadata editor and did you attach files or did you create this entirely from within R?

**Comment by earnaud** [comment]
Answering in the new issue.
