### ISSUE TITLE
rdataone for latest version of 3

### ISSUE THREAD

**Issue by ramonawalls** [DataONEorg/rdataone#235]
I just tried to install rdataone and got the following error:
`package ‘rdataone’ is not available (for R version 3.6.0)`.

I got the same error using R3.1.

Are you planning to update soon or am I missing something?

**Comment by amoeba** [comment]
Hey @ramonawalls, the R package is named 'dataone' instead of 'rdataone' so the following should work:

```r
install.packages("dataone")
```

See: https://github.com/DataONEorg/rdataone#installation-notes. This repo being named 'rdataone' while the package being named 'dataone' has tripped up folks before, myself included. R also gives the least useful and misdirecting error message I can think of which doesn't help matters much.

Let us know if that works and feel free to close this issue if it does.

**Comment by ramonawalls** [comment]
Perfect. Thanks! I thought I copied the command from somewhere, but now I cannot figure out where. If I find it, I will let you know. Probably user error though. :)
