### ISSUE TITLE
Create MNode class

### ISSUE THREAD

**Issue by mbjones** [DataONEorg/rdataone#3]
Create a MNode S4 class and implement all Member Node client-side interfaces.

- [x] Create MNode class
- [x] Implement MNode() constructor
- [x] Implement ping()
- [ ] Implement getLogRecords()
- [x] Implement getCapabilities()
- [x] Implement get()
- [x] Implement getSystemMetadata()
- [x] Implement describe()
- [x] Implement getChecksum()
- [x] Implement listObjects()
- [x] Implement create()
- [x] Implement update()
- [ ] Implement delete()
- [x] Implement archive()
- [x] Implement generateIdentifier()
- [x] Implement query()
- [x] Implement getQueryEngineDescription()
- [x] Implement listQueryEngines()

**Comment by mbjones** [comment]
From @laurenmh -- code for getChecksum():

```r
####Checksum####
## @param mnode The MNode instance from which the metadata will be downloaded
## @param pid The object identifier to be downloaded
## @param checksumAlgorithm  The algorithm to identify the checksum (default SHA-1; MD5 is a secondary DataOne supported value)
## @return checksum The comuted hash of the pid object


setGeneric("getChecksum", function(mnode, pid, checksumAlgorithm, ...) {
  standardGeneric("getChecksum")
})

setMethod("getChecksum", signature("MNode", "character"), 
          function(mnode, pid, checksumALgorithm="SHA-1") {
  url <- paste(mnode@endpoint, "checksum", pid, sep="/")
  response<-GET(url, query=list(checksumAlgorithm=checksumAlgorithm))
  checksum<-(xmlToList(xmlParse(content(response)))$text)
  return(checksum)
})
```

**Comment by sbpcs59** [comment]
Do we need CNode.delete() or MNode.delete()? The DataONE API docs indicate that this is an
administrative funciton:

From https://releases.dataone.org/online/api-documentation-v1.2.0/apis/CN_APIs.html#CNCore.delete

"The delete operation is used only by administrators in response to a request to remove an object from DataONE, perhaps because of legal requirements or the object has been identified as containing malicious content."

From https://releases.dataone.org/online/api-documentation-v1.2.0/apis/MN_APIs.html#MNStorage.delete:

The delete operation will be used primarily by Coordinating Nodes to help manage the number of replicas of an object that are present in the entire system.

**Comment by sbpcs59** [comment]
Users should call CNode::getLogRecords(), not MNode::getLogRecords() (when it is implemented)
All other functions have been implemented or accounted for (i.e. not doing delete())
