### ISSUE TITLE
convert.csv() gets stuck with large dfs

### ISSUE THREAD

**Issue by couture322** [DataONEorg/rdataone#47]
When us use convert.csv() to convert a small data frame to a csv, it works fine, but I have large data frames (~4 million rows) that do not convert. I ran the function for most of the day and over night and it was still running when I opened it in the morning.

**Comment by mbjones** [comment]
In sha d8e2495abe0d047230074a7a90bb5121d44d450f, `convert.csv()` has now been Deprecated, to avoid this in-memory issue.  The preferred mechanism to create CSV files is to use R's existing mechanisms (such as `write.csv()`) to create the CSV file.  The new v2 implementations of `MNode.create()` and `MNode.update()` take a filesystem path as an argument rather than in-memory bytes.   For example:

```r
response <- create(mn, newid, csvfile, sysmeta)
```

In a future release, we could consider allowing the `filepath` parameter in `MNode.create()` and `MNode.update()`  to be any allowable `connection`, which would allow `textConnection()` to be used for reading from a string.  In that case, the parameter could be any readable text-mode connection. Consider renaming the `filepath` parameter to `file` to allow for this future overloading of the parameter.  See documentation in `read.csv()` for a comparable example of how this could work.

**Comment by mbjones** [comment]
Added a feature request for supporting `connection()` for streaming.  With that, `convert.csv` is deprecated and no longer needed.
